@startuml

'skinparam monochrome true
'skinparam classBackgroundColor White
skinparam classArrowColor Black
skinparam classBorderColor Black
skinparam stereotypeCBackgroundColor Gray
'hide members
hide circle

class user #LightBlue {
    id
    name
    tel
    email
    avatar_id
}

class avatar {
    id
    url
}

class catagory {
    id
    name
    pid
}

class entity #LightBlue {
    id
    name
    catagory_id
    desc
    quality
    price
    create_time
    is_anonymous
}

class favorite {
    id
    user_id
    entity_id
    create_time
    is_valid
}

class comment {
    id
    content
    user_id
    entity_id
    create_time
    is_anonymous
    pid
}

class auction {
    id
    user_id
    entity_id
    price
    create_time
    is_anonymous
}

class image {
    id
    entity_id
    url
}

class action #LightGray {
    id
    name
    desc
}

class activity #LightGray {
    id
    user_id
    action_id
    desc
}

user -l-> avatar
entity -r-> catagory
catagory --> catagory : pid

image -u-> entity
favorite -u-> user
favorite -u-> entity

comment -u-> user
comment -u-> entity
comment --> comment : pid

auction -u-> user
auction -u-> entity

activity -u-> action
activity -u-> user

@enduml